### ISSUE TITLE
Search how to evaluate log loss

### ISSUE THREAD

**Issue by estevinho** [andreiarog/KaggleCompetitions#20]

**Comment by andreiarog** [comment]
Log Loss error penalizes incorrect predictions heavily. When dealing with Log Loss function, it is better to be doubtful of your prediction rather than confidently wrong. 
https://towardsdatascience.com/understanding-negative-log-loss-8c3e77fafb79

**Comment by andreiarog** [comment]
We can clip extremity results:
https://medium.com/@egor_vorobiev/how-to-improve-log-loss-score-kaggle-trick-3f95577839f1
